version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318/v1/traces
      - DATABASE_URL=postgresql://chorechat:chorechatpassword@db:5432/chorechat
    command: npm run dev
    depends_on:
      - db
      - otel-collector

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: chorechat
      POSTGRES_PASSWORD: chorechatpassword
      POSTGRES_DB: chorechat
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "chorechat"]
      interval: 10s
      timeout: 5s
      retries: 5

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4318:4318"
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
