receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:4320"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
